### PR TITLE
Fix hardcoded DH params path

### LINKED ISSUE #45: Nginx fails with "No such file or directory /etc/nginx/dh2048.pem"
It seems like the `/etc/nginx/conf.d/90.hardening.conf` is generated and after that Nginx is restarted.
This file contains the `ssl_dhparam /etc/nginx/dh2048.pem;` directive, but `execute 'generate_dh_group'` is at the end of the recipe so Nginx fails to restart...

Moving the execute resource before the template resource helps.

### PR DESCRIPTION
**Pull request by onwsk8r**
Closes #45

### CODE REVIEW

**Comment by onwsk8r** [comment]
The file that caused the linting to fail is broken in master as well. Let me know if you guys would like me to fix it here.

**Comment by chris-rock** [comment]
@onwsk8r Thank you for the improvement. Do you mind to fix the lint issues in that PR too?

```
libraries/nginx_options.rb:25:7: C: Layout/EmptyComment: Source code comment is empty.
      #
      ^
libraries/nginx_options.rb:57:7: C: Layout/EmptyComment: Source code comment is empty.
      #
      ^
```

**Comment by onwsk8r** [comment]
@chris-rock after the build failed in e5e87b2 because of the Thor version I bumped it to `~> 0.20.0`, thinking the error meant the version coveralls required was in conflict with the version that's pinned in the Gemfile. Apparently that's not the case. Again, I'm more than happy to help, but Ruby is not my strong suit. Any ideas?

**Comment by chris-rock** [comment]
@onwsk8r Thank you very much for your patience. I updated the dependencies and removed coveralls (in combination with chefdk responsible for the thor dependency issues) in https://github.com/dev-sec/chef-nginx-hardening/pull/51 Once that is merged, you can rebase your PR on master and remove the latest to commits. Once #51 is merged, you can do:
```
git fetch
git checkout master
git pull
git checkout yourbranch
git rebase -i master
git push origin yourbranch -f
```

**Pull request merged**
