### PR TITLE
Switch to chef_nginx and update testing

### PR DESCRIPTION
**Pull request by tas50**

### CODE REVIEW

**Comment by atomic111** [comment]
@tas50 thank you for your pr. i will review it in the next days.

**Comment by atomic111** [comment]
@tas50 great job!!! can you please fix the chef spec errors and then i will merge it

**Comment by chris-rock** [comment]
@tas50 Awesome. I released the current version. Could you please rebase on master. Would love to get this merged it

**Comment by chris-rock** [comment]
Thank you @tas50 for this huge improvement.

**Comment by diraol** [comment]
@chris-rock and @tas50 , did I miss understood something or on the commit 282a712f986e19b22d204b8fd8dcd0609bd1be17 there is a "merge problem" on the files ``Rakefile`` and ``metadata.rb`` ? It seems to me that, during the merging process the conflict stayed on these files.

**Comment by diraol** [comment]
Ow, I've just seen now that it is being fixed on another PR. Sorry! =)

**Comment by chris-rock** [comment]
@diraol I tried the new github merge conflict resolve feature. Although I resolve it in UI, it was not resolved in code. PR #42 is solving that

**Pull request merged**
