### PR TITLE
switch to nginx cookbook

### LINKED ISSUE #47: Update metadata to depend on "nginx" cookbook
`chef_nginx` is deprecated in favour of `nginx` (which contains all the development work done in `chef_nginx`), could you please update the `metadata.rb`?

### PR DESCRIPTION
**Pull request by rveznaver**
fixes #47

### CODE REVIEW

**Comment by rveznaver** [comment]
the tests will keep failing until #46 is merged

**Comment by atomic111** [comment]
@rveznaver thanks for the pr. i will have a look, after the pr 46 is merged

**Comment by rveznaver** [comment]
@atomic111, you're welcome! FYI; rebased on top of bb22334510541e938880d970a3c473a12891b906, tests are passing now

**Comment by chris-rock** [comment]
Thank you @rveznaver I am going to push this as 3.0.0.

**Comment by rveznaver** [comment]
Wonderful, thanks!

**Comment by chris-rock** [comment]
It is released https://github.com/dev-sec/chef-nginx-hardening/releases/tag/v3.0.0 and published to supermarket https://supermarket.chef.io/cookbooks/nginx-hardening

**Pull request merged**
