### PR TITLE
Tas50 master rebased

### PR DESCRIPTION
**Pull request by diraol**
This is the rebased version of the PullRequest #39 .

I've rebased the proposed branch upon the master branch from dev-sec to allow a fast merge.

### CODE REVIEW

**Comment by tas50** [comment]
Thanks

**Comment by atomic111** [comment]
@diraol great job! thank you. can you fix the last rubocop issue in metadata.rb.

**Comment by chris-rock** [comment]
Closed in favor of #39. Thank you @diraol for highlighting the urgency of the merge!

**Comment by diraol** [comment]
@chris-rock I'm just starting on chef and don't yet really understand what is going on, that is why I didn't fixed the last rubocop issues on metadata.rb.
But I'm glad that this issues where already addressed!

**Pull request closed without merging**
